module.exports = {

  TA_STATUS: {
    DRAFT: "DRAFT",
    SUBMITTED: "SUBMITTED",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    COMPLETED: "COMPLETED",
  },

  MILESTONE_STATUS: {
    NOT_STARTED: "NOT_STARTED",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
  },

  PROGRESS_STATUS: {
    PENDING: "PENDING",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETED: "COMPLETED",
  },

  REMINDER_STATUS: {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
    EXPIRED: "EXPIRED",
  },

  LOGBOOK_STATUS: {
    DRAFT: "DRAFT",
    REJECTED: "REJECTED",
    FINALIZED: "FINALIZED",
  }
}
